"""add_evidencias_column_to_noconformidad

Revision ID: 0551b8690aef
Revises: 3d3613f72e0b
Create Date: 2026-02-13 17:59:45.771393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0551b8690aef'
down_revision: Union[str, Sequence[str], None] = '3d3613f72e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('no_conformidades', sa.Column('evidencias', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('no_conformidades', 'evidencias')
    # ### end Alembic commands ###
