"""implementar_plan_auditorias_iso

Revision ID: 153ce9ca0521
Revises: 0551b8690aef
Create Date: 2026-02-13 20:44:02.116410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153ce9ca0521'
down_revision: Union[str, Sequence[str], None] = '0551b8690aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_estados',
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('historial_entidad', 'historial_estados', ['entidad_tipo', 'entidad_id'], unique=False)
    op.create_table('programa_auditorias',
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('aprobado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('criterio_riesgo', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auditorias', sa.Column('programa_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'auditorias', 'programa_auditorias', ['programa_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('hallazgo_auditorias', sa.Column('no_conformidad_id', sa.UUID(), nullable=True))
    op.add_column('hallazgo_auditorias', sa.Column('verificado_por', sa.UUID(), nullable=True))
    op.add_column('hallazgo_auditorias', sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hallazgo_auditorias', sa.Column('resultado_verificacion', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'hallazgo_auditorias', 'usuarios', ['verificado_por'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'hallazgo_auditorias', 'no_conformidades', ['no_conformidad_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hallazgo_auditorias', type_='foreignkey')
    op.drop_constraint(None, 'hallazgo_auditorias', type_='foreignkey')
    op.drop_column('hallazgo_auditorias', 'resultado_verificacion')
    op.drop_column('hallazgo_auditorias', 'fecha_verificacion')
    op.drop_column('hallazgo_auditorias', 'verificado_por')
    op.drop_column('hallazgo_auditorias', 'no_conformidad_id')
    op.drop_constraint(None, 'auditorias', type_='foreignkey')
    op.drop_column('auditorias', 'programa_id')
    op.drop_table('programa_auditorias')
    op.drop_index('historial_entidad', table_name='historial_estados')
    op.drop_table('historial_estados')
    # ### end Alembic commands ###
