"""add revisado_por to documentos

Revision ID: 3d3613f72e0b
Revises: 276ac738101f
Create Date: 2026-02-12 20:47:09.363872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3613f72e0b'
down_revision: Union[str, Sequence[str], None] = '276ac738101f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('revisado_por', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documentos', 'usuarios', ['revisado_por'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_column('documentos', 'revisado_por')
    # ### end Alembic commands ###
