"""Add competencias module

Revision ID: 4566e18563e6
Revises: 001_add_gravedad
Create Date: 2026-01-27 23:05:13.309838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4566e18563e6'
down_revision: Union[str, Sequence[str], None] = '001_add_gravedad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencias',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('evaluaciones_competencia',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('competencia_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluador_id', sa.UUID(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencias.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Validar si la columna existe antes de eliminarla (Fix para entornos donde ya fue eliminada)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('auditorias')]
    if 'norma_referencia' in columns:
        op.drop_column('auditorias', 'norma_referencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditorias', sa.Column('norma_referencia', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_table('evaluaciones_competencia')
    op.drop_table('competencias')
    # ### end Alembic commands ###
