"""add implementado_por and evidencias to acciones_correctivas

Revision ID: d26d2d18bd32
Revises: 05b1c1a5e3d5
Create Date: 2026-02-04 11:04:02.989175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26d2d18bd32'
down_revision: Union[str, Sequence[str], None] = '05b1c1a5e3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acciones_correctivas', sa.Column('implementado_por', sa.UUID(), nullable=True))
    op.add_column('acciones_correctivas', sa.Column('evidencias', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'acciones_correctivas', 'usuarios', ['implementado_por'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('tickets', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tickets', 'solicitante_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('tickets_codigo'), table_name='tickets')
    op.drop_constraint(op.f('tickets_codigo_key'), 'tickets', type_='unique')
    op.drop_index(op.f('tickets_estado'), table_name='tickets')
    op.drop_constraint(op.f('tickets_solicitante_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_area_destino'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_asignado_a_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'areas', ['area_destino_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'usuarios', ['solicitante_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'usuarios', ['asignado_a'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_asignado_a_fkey'), 'tickets', 'usuarios', ['asignado_a'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_area_destino'), 'tickets', 'areas', ['area_destino_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tickets_solicitante_id_fkey'), 'tickets', 'usuarios', ['solicitante_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index(op.f('tickets_estado'), 'tickets', ['estado'], unique=False)
    op.create_unique_constraint(op.f('tickets_codigo_key'), 'tickets', ['codigo'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('tickets_codigo'), 'tickets', ['codigo'], unique=False)
    op.alter_column('tickets', 'solicitante_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tickets', 'categoria',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'acciones_correctivas', type_='foreignkey')
    op.drop_column('acciones_correctivas', 'evidencias')
    op.drop_column('acciones_correctivas', 'implementado_por')
    # ### end Alembic commands ###
