"""implementar_plan_auditorias_iso

Revision ID: d69e42bdb645
Revises: 153ce9ca0521
Create Date: 2026-02-13 20:52:23.013584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69e42bdb645'
down_revision: Union[str, Sequence[str], None] = '153ce9ca0521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
