"""create tickets table

Revision ID: e5244117f219
Revises: 4566e18563e6
Create Date: 2026-01-28 23:15:43.117731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5244117f219'
down_revision: Union[str, Sequence[str], None] = '4566e18563e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SequelizeMeta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SequelizeMeta',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('SequelizeMeta_pkey'))
    )
    # ### end Alembic commands ###
