"""add_responsables_proceso_table

Revision ID: f50e73029ab7
Revises: f1b2c3d4e5f6
Create Date: 2026-02-19 19:06:01.322951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50e73029ab7'
down_revision: Union[str, Sequence[str], None] = 'f1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsables_proceso',
    sa.Column('proceso_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso_id', 'usuario_id', 'rol', name='responsables_proceso_unique')
    )
    op.create_index('idx_responsables_proceso_proceso', 'responsables_proceso', ['proceso_id'], unique=False)
    op.create_index('idx_responsables_proceso_usuario', 'responsables_proceso', ['usuario_id'], unique=False)
    op.drop_index(op.f('idx_auditorias_proceso_id'), table_name='auditorias')
    op.drop_index(op.f('idx_brechas_competencia_competencia'), table_name='brechas_competencia')
    op.drop_index(op.f('idx_brechas_competencia_estado'), table_name='brechas_competencia')
    op.drop_index(op.f('idx_brechas_competencia_usuario'), table_name='brechas_competencia')
    op.drop_index(op.f('idx_campo_formularios_formulario_id'), table_name='campo_formularios')
    op.drop_index(op.f('idx_capacitaciones_area_id'), table_name='capacitaciones')
    op.drop_index(op.f('idx_respuesta_formularios_auditoria_id'), table_name='respuesta_formularios')
    op.drop_constraint(op.f('fk_tickets_documento_publico'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'documentos', ['documento_publico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_documento_publico'), 'tickets', 'documentos', ['documento_publico_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_respuesta_formularios_auditoria_id'), 'respuesta_formularios', ['auditoria_id'], unique=False)
    op.create_index(op.f('idx_capacitaciones_area_id'), 'capacitaciones', ['area_id'], unique=False)
    op.create_index(op.f('idx_campo_formularios_formulario_id'), 'campo_formularios', ['formulario_id'], unique=False)
    op.create_index(op.f('idx_brechas_competencia_usuario'), 'brechas_competencia', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_brechas_competencia_estado'), 'brechas_competencia', ['estado'], unique=False)
    op.create_index(op.f('idx_brechas_competencia_competencia'), 'brechas_competencia', ['competencia_id'], unique=False)
    op.create_index(op.f('idx_auditorias_proceso_id'), 'auditorias', ['proceso_id'], unique=False)
    op.drop_index('idx_responsables_proceso_usuario', table_name='responsables_proceso')
    op.drop_index('idx_responsables_proceso_proceso', table_name='responsables_proceso')
    op.drop_table('responsables_proceso')
    # ### end Alembic commands ###
